/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BuySellUsedPhonesPrescotRouteImport } from './routes/buy-sell-used-phones-prescot'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as DesignLabRouteImport } from './routes/design-lab'
import { Route as GamingConsoleRepairPrescotRouteImport } from './routes/gaming-console-repair-prescot'
import { Route as LaptopComputerRepairPrescotRouteImport } from './routes/laptop-computer-repair-prescot'
import { Route as MobilePhoneRepairPrescotRouteImport } from './routes/mobile-phone-repair-prescot'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as RefundsRouteImport } from './routes/refunds'
import { Route as RepairTermsRouteImport } from './routes/repair-terms'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WarrantyRouteImport } from './routes/warranty'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardCustomersRouteImport } from './routes/_authenticated/dashboard.customers'
import { Route as AuthenticatedDashboardDailySalesRouteImport } from './routes/_authenticated/dashboard.daily-sales'
import { Route as AuthenticatedDashboardExpensesRouteImport } from './routes/_authenticated/dashboard.expenses'
import { Route as AuthenticatedDashboardPhoneBuySellRouteImport } from './routes/_authenticated/dashboard.phone-buy-sell'
import { Route as AuthenticatedDashboardPosRouteImport } from './routes/_authenticated/dashboard.pos'
import { Route as AuthenticatedDashboardProductsRouteImport } from './routes/_authenticated/dashboard.products'
import { Route as AuthenticatedDashboardPurchasesRouteImport } from './routes/_authenticated/dashboard.purchases'
import { Route as AuthenticatedDashboardRepairsRouteImport } from './routes/_authenticated/dashboard.repairs'
import { Route as AuthenticatedDashboardReportsRouteImport } from './routes/_authenticated/dashboard.reports'
import { Route as AuthenticatedDashboardSalesRouteImport } from './routes/_authenticated/dashboard.sales'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard.settings'
import { Route as AuthenticatedDashboardSuppliersRouteImport } from './routes/_authenticated/dashboard.suppliers'
import { Route as AuthenticatedDashboardUsersRouteImport } from './routes/_authenticated/dashboard.users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BuySellUsedPhonesPrescotRoute =
  BuySellUsedPhonesPrescotRouteImport.update({
    id: '/buy-sell-used-phones-prescot',
    path: '/buy-sell-used-phones-prescot',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignLabRoute = DesignLabRouteImport.update({
  id: '/design-lab',
  path: '/design-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const GamingConsoleRepairPrescotRoute =
  GamingConsoleRepairPrescotRouteImport.update({
    id: '/gaming-console-repair-prescot',
    path: '/gaming-console-repair-prescot',
    getParentRoute: () => rootRouteImport,
  } as any)
const LaptopComputerRepairPrescotRoute =
  LaptopComputerRepairPrescotRouteImport.update({
    id: '/laptop-computer-repair-prescot',
    path: '/laptop-computer-repair-prescot',
    getParentRoute: () => rootRouteImport,
  } as any)
const MobilePhoneRepairPrescotRoute =
  MobilePhoneRepairPrescotRouteImport.update({
    id: '/mobile-phone-repair-prescot',
    path: '/mobile-phone-repair-prescot',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsRoute = RefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const RepairTermsRoute = RepairTermsRouteImport.update({
  id: '/repair-terms',
  path: '/repair-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WarrantyRoute = WarrantyRouteImport.update({
  id: '/warranty',
  path: '/warranty',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCustomersRoute =
  AuthenticatedDashboardCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardDailySalesRoute =
  AuthenticatedDashboardDailySalesRouteImport.update({
    id: '/daily-sales',
    path: '/daily-sales',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardExpensesRoute =
  AuthenticatedDashboardExpensesRouteImport.update({
    id: '/expenses',
    path: '/expenses',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPhoneBuySellRoute =
  AuthenticatedDashboardPhoneBuySellRouteImport.update({
    id: '/phone-buy-sell',
    path: '/phone-buy-sell',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPosRoute =
  AuthenticatedDashboardPosRouteImport.update({
    id: '/pos',
    path: '/pos',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProductsRoute =
  AuthenticatedDashboardProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPurchasesRoute =
  AuthenticatedDashboardPurchasesRouteImport.update({
    id: '/purchases',
    path: '/purchases',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardRepairsRoute =
  AuthenticatedDashboardRepairsRouteImport.update({
    id: '/repairs',
    path: '/repairs',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardReportsRoute =
  AuthenticatedDashboardReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSalesRoute =
  AuthenticatedDashboardSalesRouteImport.update({
    id: '/sales',
    path: '/sales',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSuppliersRoute =
  AuthenticatedDashboardSuppliersRouteImport.update({
    id: '/suppliers',
    path: '/suppliers',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardUsersRoute =
  AuthenticatedDashboardUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/auth': typeof AuthRoute
  '/buy-sell-used-phones-prescot': typeof BuySellUsedPhonesPrescotRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/design-lab': typeof DesignLabRoute
  '/gaming-console-repair-prescot': typeof GamingConsoleRepairPrescotRoute
  '/laptop-computer-repair-prescot': typeof LaptopComputerRepairPrescotRoute
  '/mobile-phone-repair-prescot': typeof MobilePhoneRepairPrescotRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/refunds': typeof RefundsRoute
  '/repair-terms': typeof RepairTermsRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/warranty': typeof WarrantyRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/dashboard/customers': typeof AuthenticatedDashboardCustomersRoute
  '/dashboard/daily-sales': typeof AuthenticatedDashboardDailySalesRoute
  '/dashboard/expenses': typeof AuthenticatedDashboardExpensesRoute
  '/dashboard/phone-buy-sell': typeof AuthenticatedDashboardPhoneBuySellRoute
  '/dashboard/pos': typeof AuthenticatedDashboardPosRoute
  '/dashboard/products': typeof AuthenticatedDashboardProductsRoute
  '/dashboard/purchases': typeof AuthenticatedDashboardPurchasesRoute
  '/dashboard/repairs': typeof AuthenticatedDashboardRepairsRoute
  '/dashboard/reports': typeof AuthenticatedDashboardReportsRoute
  '/dashboard/sales': typeof AuthenticatedDashboardSalesRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/suppliers': typeof AuthenticatedDashboardSuppliersRoute
  '/dashboard/users': typeof AuthenticatedDashboardUsersRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/auth': typeof AuthRoute
  '/buy-sell-used-phones-prescot': typeof BuySellUsedPhonesPrescotRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/design-lab': typeof DesignLabRoute
  '/gaming-console-repair-prescot': typeof GamingConsoleRepairPrescotRoute
  '/laptop-computer-repair-prescot': typeof LaptopComputerRepairPrescotRoute
  '/mobile-phone-repair-prescot': typeof MobilePhoneRepairPrescotRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/refunds': typeof RefundsRoute
  '/repair-terms': typeof RepairTermsRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/warranty': typeof WarrantyRoute
  '/dashboard/customers': typeof AuthenticatedDashboardCustomersRoute
  '/dashboard/daily-sales': typeof AuthenticatedDashboardDailySalesRoute
  '/dashboard/expenses': typeof AuthenticatedDashboardExpensesRoute
  '/dashboard/phone-buy-sell': typeof AuthenticatedDashboardPhoneBuySellRoute
  '/dashboard/pos': typeof AuthenticatedDashboardPosRoute
  '/dashboard/products': typeof AuthenticatedDashboardProductsRoute
  '/dashboard/purchases': typeof AuthenticatedDashboardPurchasesRoute
  '/dashboard/repairs': typeof AuthenticatedDashboardRepairsRoute
  '/dashboard/reports': typeof AuthenticatedDashboardReportsRoute
  '/dashboard/sales': typeof AuthenticatedDashboardSalesRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/suppliers': typeof AuthenticatedDashboardSuppliersRoute
  '/dashboard/users': typeof AuthenticatedDashboardUsersRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/auth': typeof AuthRoute
  '/buy-sell-used-phones-prescot': typeof BuySellUsedPhonesPrescotRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/design-lab': typeof DesignLabRoute
  '/gaming-console-repair-prescot': typeof GamingConsoleRepairPrescotRoute
  '/laptop-computer-repair-prescot': typeof LaptopComputerRepairPrescotRoute
  '/mobile-phone-repair-prescot': typeof MobilePhoneRepairPrescotRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/refunds': typeof RefundsRoute
  '/repair-terms': typeof RepairTermsRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/warranty': typeof WarrantyRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/dashboard/customers': typeof AuthenticatedDashboardCustomersRoute
  '/_authenticated/dashboard/daily-sales': typeof AuthenticatedDashboardDailySalesRoute
  '/_authenticated/dashboard/expenses': typeof AuthenticatedDashboardExpensesRoute
  '/_authenticated/dashboard/phone-buy-sell': typeof AuthenticatedDashboardPhoneBuySellRoute
  '/_authenticated/dashboard/pos': typeof AuthenticatedDashboardPosRoute
  '/_authenticated/dashboard/products': typeof AuthenticatedDashboardProductsRoute
  '/_authenticated/dashboard/purchases': typeof AuthenticatedDashboardPurchasesRoute
  '/_authenticated/dashboard/repairs': typeof AuthenticatedDashboardRepairsRoute
  '/_authenticated/dashboard/reports': typeof AuthenticatedDashboardReportsRoute
  '/_authenticated/dashboard/sales': typeof AuthenticatedDashboardSalesRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/_authenticated/dashboard/suppliers': typeof AuthenticatedDashboardSuppliersRoute
  '/_authenticated/dashboard/users': typeof AuthenticatedDashboardUsersRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessibility'
    | '/auth'
    | '/buy-sell-used-phones-prescot'
    | '/contact'
    | '/cookies'
    | '/design-lab'
    | '/gaming-console-repair-prescot'
    | '/laptop-computer-repair-prescot'
    | '/mobile-phone-repair-prescot'
    | '/privacy'
    | '/products'
    | '/refunds'
    | '/repair-terms'
    | '/reviews'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/warranty'
    | '/dashboard'
    | '/dashboard/customers'
    | '/dashboard/daily-sales'
    | '/dashboard/expenses'
    | '/dashboard/phone-buy-sell'
    | '/dashboard/pos'
    | '/dashboard/products'
    | '/dashboard/purchases'
    | '/dashboard/repairs'
    | '/dashboard/reports'
    | '/dashboard/sales'
    | '/dashboard/settings'
    | '/dashboard/suppliers'
    | '/dashboard/users'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessibility'
    | '/auth'
    | '/buy-sell-used-phones-prescot'
    | '/contact'
    | '/cookies'
    | '/design-lab'
    | '/gaming-console-repair-prescot'
    | '/laptop-computer-repair-prescot'
    | '/mobile-phone-repair-prescot'
    | '/privacy'
    | '/products'
    | '/refunds'
    | '/repair-terms'
    | '/reviews'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/warranty'
    | '/dashboard/customers'
    | '/dashboard/daily-sales'
    | '/dashboard/expenses'
    | '/dashboard/phone-buy-sell'
    | '/dashboard/pos'
    | '/dashboard/products'
    | '/dashboard/purchases'
    | '/dashboard/repairs'
    | '/dashboard/reports'
    | '/dashboard/sales'
    | '/dashboard/settings'
    | '/dashboard/suppliers'
    | '/dashboard/users'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/accessibility'
    | '/auth'
    | '/buy-sell-used-phones-prescot'
    | '/contact'
    | '/cookies'
    | '/design-lab'
    | '/gaming-console-repair-prescot'
    | '/laptop-computer-repair-prescot'
    | '/mobile-phone-repair-prescot'
    | '/privacy'
    | '/products'
    | '/refunds'
    | '/repair-terms'
    | '/reviews'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/warranty'
    | '/_authenticated/dashboard'
    | '/_authenticated/dashboard/customers'
    | '/_authenticated/dashboard/daily-sales'
    | '/_authenticated/dashboard/expenses'
    | '/_authenticated/dashboard/phone-buy-sell'
    | '/_authenticated/dashboard/pos'
    | '/_authenticated/dashboard/products'
    | '/_authenticated/dashboard/purchases'
    | '/_authenticated/dashboard/repairs'
    | '/_authenticated/dashboard/reports'
    | '/_authenticated/dashboard/sales'
    | '/_authenticated/dashboard/settings'
    | '/_authenticated/dashboard/suppliers'
    | '/_authenticated/dashboard/users'
    | '/_authenticated/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  AuthRoute: typeof AuthRoute
  BuySellUsedPhonesPrescotRoute: typeof BuySellUsedPhonesPrescotRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  DesignLabRoute: typeof DesignLabRoute
  GamingConsoleRepairPrescotRoute: typeof GamingConsoleRepairPrescotRoute
  LaptopComputerRepairPrescotRoute: typeof LaptopComputerRepairPrescotRoute
  MobilePhoneRepairPrescotRoute: typeof MobilePhoneRepairPrescotRoute
  PrivacyRoute: typeof PrivacyRoute
  ProductsRoute: typeof ProductsRoute
  RefundsRoute: typeof RefundsRoute
  RepairTermsRoute: typeof RepairTermsRoute
  ReviewsRoute: typeof ReviewsRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  WarrantyRoute: typeof WarrantyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy-sell-used-phones-prescot': {
      id: '/buy-sell-used-phones-prescot'
      path: '/buy-sell-used-phones-prescot'
      fullPath: '/buy-sell-used-phones-prescot'
      preLoaderRoute: typeof BuySellUsedPhonesPrescotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-lab': {
      id: '/design-lab'
      path: '/design-lab'
      fullPath: '/design-lab'
      preLoaderRoute: typeof DesignLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gaming-console-repair-prescot': {
      id: '/gaming-console-repair-prescot'
      path: '/gaming-console-repair-prescot'
      fullPath: '/gaming-console-repair-prescot'
      preLoaderRoute: typeof GamingConsoleRepairPrescotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laptop-computer-repair-prescot': {
      id: '/laptop-computer-repair-prescot'
      path: '/laptop-computer-repair-prescot'
      fullPath: '/laptop-computer-repair-prescot'
      preLoaderRoute: typeof LaptopComputerRepairPrescotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile-phone-repair-prescot': {
      id: '/mobile-phone-repair-prescot'
      path: '/mobile-phone-repair-prescot'
      fullPath: '/mobile-phone-repair-prescot'
      preLoaderRoute: typeof MobilePhoneRepairPrescotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds': {
      id: '/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof RefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repair-terms': {
      id: '/repair-terms'
      path: '/repair-terms'
      fullPath: '/repair-terms'
      preLoaderRoute: typeof RepairTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warranty': {
      id: '/warranty'
      path: '/warranty'
      fullPath: '/warranty'
      preLoaderRoute: typeof WarrantyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/customers': {
      id: '/_authenticated/dashboard/customers'
      path: '/customers'
      fullPath: '/dashboard/customers'
      preLoaderRoute: typeof AuthenticatedDashboardCustomersRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/daily-sales': {
      id: '/_authenticated/dashboard/daily-sales'
      path: '/daily-sales'
      fullPath: '/dashboard/daily-sales'
      preLoaderRoute: typeof AuthenticatedDashboardDailySalesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/expenses': {
      id: '/_authenticated/dashboard/expenses'
      path: '/expenses'
      fullPath: '/dashboard/expenses'
      preLoaderRoute: typeof AuthenticatedDashboardExpensesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/phone-buy-sell': {
      id: '/_authenticated/dashboard/phone-buy-sell'
      path: '/phone-buy-sell'
      fullPath: '/dashboard/phone-buy-sell'
      preLoaderRoute: typeof AuthenticatedDashboardPhoneBuySellRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/pos': {
      id: '/_authenticated/dashboard/pos'
      path: '/pos'
      fullPath: '/dashboard/pos'
      preLoaderRoute: typeof AuthenticatedDashboardPosRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/products': {
      id: '/_authenticated/dashboard/products'
      path: '/products'
      fullPath: '/dashboard/products'
      preLoaderRoute: typeof AuthenticatedDashboardProductsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/purchases': {
      id: '/_authenticated/dashboard/purchases'
      path: '/purchases'
      fullPath: '/dashboard/purchases'
      preLoaderRoute: typeof AuthenticatedDashboardPurchasesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/repairs': {
      id: '/_authenticated/dashboard/repairs'
      path: '/repairs'
      fullPath: '/dashboard/repairs'
      preLoaderRoute: typeof AuthenticatedDashboardRepairsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/reports': {
      id: '/_authenticated/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof AuthenticatedDashboardReportsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/sales': {
      id: '/_authenticated/dashboard/sales'
      path: '/sales'
      fullPath: '/dashboard/sales'
      preLoaderRoute: typeof AuthenticatedDashboardSalesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/suppliers': {
      id: '/_authenticated/dashboard/suppliers'
      path: '/suppliers'
      fullPath: '/dashboard/suppliers'
      preLoaderRoute: typeof AuthenticatedDashboardSuppliersRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/users': {
      id: '/_authenticated/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof AuthenticatedDashboardUsersRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardCustomersRoute: typeof AuthenticatedDashboardCustomersRoute
  AuthenticatedDashboardDailySalesRoute: typeof AuthenticatedDashboardDailySalesRoute
  AuthenticatedDashboardExpensesRoute: typeof AuthenticatedDashboardExpensesRoute
  AuthenticatedDashboardPhoneBuySellRoute: typeof AuthenticatedDashboardPhoneBuySellRoute
  AuthenticatedDashboardPosRoute: typeof AuthenticatedDashboardPosRoute
  AuthenticatedDashboardProductsRoute: typeof AuthenticatedDashboardProductsRoute
  AuthenticatedDashboardPurchasesRoute: typeof AuthenticatedDashboardPurchasesRoute
  AuthenticatedDashboardRepairsRoute: typeof AuthenticatedDashboardRepairsRoute
  AuthenticatedDashboardReportsRoute: typeof AuthenticatedDashboardReportsRoute
  AuthenticatedDashboardSalesRoute: typeof AuthenticatedDashboardSalesRoute
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardSuppliersRoute: typeof AuthenticatedDashboardSuppliersRoute
  AuthenticatedDashboardUsersRoute: typeof AuthenticatedDashboardUsersRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardCustomersRoute: AuthenticatedDashboardCustomersRoute,
    AuthenticatedDashboardDailySalesRoute:
      AuthenticatedDashboardDailySalesRoute,
    AuthenticatedDashboardExpensesRoute: AuthenticatedDashboardExpensesRoute,
    AuthenticatedDashboardPhoneBuySellRoute:
      AuthenticatedDashboardPhoneBuySellRoute,
    AuthenticatedDashboardPosRoute: AuthenticatedDashboardPosRoute,
    AuthenticatedDashboardProductsRoute: AuthenticatedDashboardProductsRoute,
    AuthenticatedDashboardPurchasesRoute: AuthenticatedDashboardPurchasesRoute,
    AuthenticatedDashboardRepairsRoute: AuthenticatedDashboardRepairsRoute,
    AuthenticatedDashboardReportsRoute: AuthenticatedDashboardReportsRoute,
    AuthenticatedDashboardSalesRoute: AuthenticatedDashboardSalesRoute,
    AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
    AuthenticatedDashboardSuppliersRoute: AuthenticatedDashboardSuppliersRoute,
    AuthenticatedDashboardUsersRoute: AuthenticatedDashboardUsersRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  AuthRoute: AuthRoute,
  BuySellUsedPhonesPrescotRoute: BuySellUsedPhonesPrescotRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  DesignLabRoute: DesignLabRoute,
  GamingConsoleRepairPrescotRoute: GamingConsoleRepairPrescotRoute,
  LaptopComputerRepairPrescotRoute: LaptopComputerRepairPrescotRoute,
  MobilePhoneRepairPrescotRoute: MobilePhoneRepairPrescotRoute,
  PrivacyRoute: PrivacyRoute,
  ProductsRoute: ProductsRoute,
  RefundsRoute: RefundsRoute,
  RepairTermsRoute: RepairTermsRoute,
  ReviewsRoute: ReviewsRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  WarrantyRoute: WarrantyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
